name: CodeSonar
on:
  push:                  # Only run onces the Pull request is created
    branches:
      - 'release/**'               # Feature Branches
  pull_request:
    branches:
      - 'release/**'       
  
jobs:
  CodeSonar_Analyze:
    permissions: write-all
    runs-on: codesecure-runner-set
    container:
      image: ghcr.io/codesecure-se/curl-cso-builder:8.1p0

    env:
      ROOT_TREE: "OSS-Projects/curl-GitHub" 
      PROJECT_NAME: "curl"
      REPO_URL: "https://github.com/CodeSecure-SE/curl"  
      # GITHUB does not copy secrets and vars to the environment, so we need to set them manually
      GITHUB_TOKEN: ${{ secrets.github_token }} 
      CSONAR_HUB_PASSWORD: ${{ secrets.CSONAR_HUB_PASSWORD }}
      CSONAR_HUB_USER: ${{ vars.CSONAR_HUB_USER }}
      CSONAR_HUB_URL: ${{ vars.CSONAR_HUB_URL }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Safe directory
        run: git config --global --add safe.directory `pwd`
      - name : configure
        run: autoreconf -fi; ./configure --with-openssl
      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v4
        with:
          repository: CodeSecure-SE/codesonar_ci
          ref: feature/auto-set-vars
          path: cso-scripts
      - name: Build and Analyze
        run: python3 cso-scripts/build_and_analyze.py codesonar.conf make -j $(nproc)
#      - name: Upload SARIF to GitHub #Use this if you do not have GitHub Enterprise
#        if: ${{ github.event.pull_request }}
#        uses: actions/upload-artifact@v3
#        with:
#          name: SARIF file
#          path: warnings.sarif
      - name: Push Summary Report
        if: ${{ github.event.pull_request }}
        uses: thollander/actions-comment-pull-request@v2
        with: 
          filePath: warnings.md
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: warnings.sarif
          category: "CodeSecure CodeSonar"    
          wait-for-processing: false   

